name: Android Build

on:
  push:
    branches:
      - 'master'

jobs: 
  build: 

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Branch
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Project
        run: ./gradlew assemble

      - run: mkdir -p outputs/
      - run: find . -type f -regex ".*\/*\.apk" -exec cp {} outputs/ \;

      - name: Release Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Builds
          path: outputs/
          
